name: Continuous Integration
# This workflow is triggered on pushes to the repository.
on: 
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }} # runs a test on Ubuntu, Windows and macOS
    strategy:
      matrix:
        os: [macOS-latest, windows-latest, ubuntu-latest]
    steps:
      - name: Build components
        run: |
          echo 'Building components and sandbox'
          npm run build
